### ISSUE TITLE
 I want to learn with my data, but I found an error.

### ISSUE THREAD

**Issue by HONG-DEOK** [ziqi-jin/finetune-anything#39]
Traceback (most recent call last):
  File "D:\3. Develop\2.AI\segmentation_anything_yaml\train.py", line 32, in <module>
    train_dataset = get_dataset(train_cfg.dataset)
  File "D:\segmentation_anything_yaml\datasets\__init__.py", line 28, in get_dataset
    return segment_datasets[name](**cfg.params, transform=transform, target_transform=target_transform)
TypeError: __init__() got an unexpected keyword argument 'root'

How can I resolve TypeError?
![a](https://github.com/ziqi-jin/finetune-anything/assets/48157109/a7d44dfb-5a4f-47c5-87da-e73ba4ff3c1b)

I think it's a version issue. Can you tell me your version?
my cuda is 11.3, cudnn is v8.2.0.53

**Comment by ziqi-jin** [comment]
my cuda is 10.2, the error seems that tell you there is a unexcepted parameter named 'root'

**Comment by Caz-T** [comment]
I guess you might have specified your own dataset class and left some parameters unchanged. In the configuration yaml file, the key `name` referes to the name of the dataset *class* rather than that of the dataset itself. If you're not using the default VOC dataset (say, `BaseSematicDataset`) you'll need to remove the key `root` since in `BaseSematicDataset` class you don't need a root parameter.

**Comment by zsy7532** [comment]
How do you solve this problem?I met the same problem.

**Comment by AymanTalkhani** [comment]
@HONG-DEOK @Caz-T @zsy7532 We've actually built out a platform that finetunes a research variant of SAM for labeling purposes at [InstaLabel](https://www.instalabel.ai/). All you need to do is upload your dataset, select and label a few samples you'd like to finetune the model on in our platform, and hit the 'Train annotator' button. You can then head over to the 'Annotate' tab, click 'Instant Annotation' and have the finetuned model label the rest of your dataset for you. We also offer crowdsourcing if you'd like to correct the AI predictions for verified ground truth labels. Should be useful if you're interested in learning from your data while labeling it to train your models!
