### ISSUE TITLE
Why tensors can not be aligned?

### ISSUE THREAD

**Issue by Roomnum** [ziqi-jin/finetune-anything#59]
Hello @ziqi-jin, thanks for your incredible contribution!
When I run python train.py, it shows some problems below:
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    runner.train(train_cfg)
  File "/home/wyj/518/fjh/finetune-anything/extend_sam/runner.py", line 64, in train
    self._compute_loss(total_loss, loss_dict, masks_pred, labels, cfg)
  File "/home/wyj/518/fjh/finetune-anything/extend_sam/runner.py", line 128, in _compute_loss
    tmp_loss = item[1](mask_pred, real_labels)
  File "/home/wyj/miniconda3/envs/fa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyj/miniconda3/envs/fa/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/wyj/miniconda3/envs/fa/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [2, 1024, 1024, 4]

**Comment by Roomnum** [comment]
> Hello @ziqi-jin, thanks for your incredible contribution! When I run python train.py, it shows some problems below: Traceback (most recent call last): File "train.py", line 45, in runner.train(train_cfg) File "/home/wyj/518/fjh/finetune-anything/extend_sam/runner.py", line 64, in train self._compute_loss(total_loss, loss_dict, masks_pred, labels, cfg) File "/home/wyj/518/fjh/finetune-anything/extend_sam/runner.py", line 128, in _compute_loss tmp_loss = item[1](mask_pred, real_labels) File "/home/wyj/miniconda3/envs/fa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/wyj/miniconda3/envs/fa/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward return F.cross_entropy(input, target, weight=self.weight, File "/home/wyj/miniconda3/envs/fa/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing) RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [2, 1024, 1024, 4]

And I was wondering why it is four-dimension
